# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_artigo', models.CharField(max_length=250)),
                ('quantidade_autores_artigo', models.PositiveIntegerField()),
                ('texto_artigo', models.TextField()),
                ('data_publicacao_artigo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=50)),
                ('id_artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pln.Artigos')),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_genero', models.CharField(max_length=20)),
                ('quantidade_artigo_genero', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiraresposta_questionario', models.IntegerField()),
                ('segundaresposta_questionario', models.IntegerField()),
                ('terceiraresposta_questionario', models.CharField(max_length=3)),
                ('quartaresposta_questionario', models.CharField(max_length=3)),
                ('data_resposta_questionario', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Restricoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_restricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='questionario',
            name='id_restricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pln.Restricoes'),
        ),
        migrations.AddField(
            model_name='artigos',
            name='id_genero_artigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pln.Generos'),
        ),
    ]
