# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 18:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pln', '0002_auto_20170606_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='data_resposta_questionario',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 15, 20, 2, 846030)),
        ),
    ]
